--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04/04/2019 10:12:59
-- Server version: 5.5.5-10.1.36-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE db2018_python;

--
-- Drop table `aemet`
--
DROP TABLE IF EXISTS aemet;

--
-- Drop table `python`
--
DROP TABLE IF EXISTS python;

--
-- Set default database
--
USE db2018_python;

--
-- Create table `python`
--
CREATE TABLE python (
  id int(11) NOT NULL AUTO_INCREMENT,
  instante datetime DEFAULT NULL,
  edad int(11) DEFAULT NULL,
  nacimiento int(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 4096,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `aemet`
--
CREATE TABLE aemet (
  id int(11) NOT NULL AUTO_INCREMENT,
  fecha date DEFAULT NULL,
  lluvia int(11) DEFAULT NULL,
  insercion datetime DEFAULT NULL,
  f_prediccion date DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 22,
AVG_ROW_LENGTH = 1365,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `fecha` on table `aemet`
--
ALTER TABLE aemet
ADD UNIQUE INDEX fecha (fecha, f_prediccion);

-- 
-- Dumping data for table python
--
INSERT INTO python VALUES
(1, '2019-04-03 11:10:43', NULL, NULL),
(4, '2019-04-03 11:19:21', NULL, NULL),
(5, '2019-04-03 11:20:20', NULL, NULL),
(6, '2019-04-03 11:33:34', NULL, NULL),
(7, '2019-04-03 11:39:16', 42, 1977);

-- 
-- Dumping data for table aemet
--
INSERT INTO aemet VALUES
(2, '2019-04-04', 100, '2019-04-03 14:03:42', '2019-04-03'),
(3, '2019-04-05', 100, '2019-04-03 14:03:42', '2019-04-03'),
(4, '2019-04-06', 90, '2019-04-03 14:03:42', '2019-04-03'),
(5, '2019-04-07', 95, '2019-04-03 14:03:42', '2019-04-03'),
(6, '2019-04-08', 65, '2019-04-03 14:03:42', '2019-04-03'),
(7, '2019-04-09', 80, '2019-04-03 14:03:42', '2019-04-03'),
(16, '2019-04-05', 100, '2019-04-04 10:02:49', '2019-04-04'),
(17, '2019-04-06', 90, '2019-04-04 10:02:49', '2019-04-04'),
(18, '2019-04-07', 90, '2019-04-04 10:02:49', '2019-04-04'),
(19, '2019-04-08', 90, '2019-04-04 10:02:49', '2019-04-04'),
(20, '2019-04-09', 80, '2019-04-04 10:02:49', '2019-04-04'),
(21, '2019-04-10', 85, '2019-04-04 10:02:49', '2019-04-04');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;